import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from './components/Header';
import { Provider } from 'jotai';
import ThemeWrapper from './contexts/ThemeWrapper';
import ThemeProvider from './contexts/ThemeContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Provider>
          <ThemeProvider>
            <ThemeWrapper>
              <Header />
              <main>{children}</main>
            </ThemeWrapper>
          </ThemeProvider>
        </Provider>
      </body>
    </html>
  );
}
