export const RATES = [
  { currency: 'EUR', fullName: 'Euro' },
  { currency: 'AED', fullName: 'United Arab Emirates Dirham' },
  { currency: 'AFN', fullName: 'Afghan Afghani' },
  { currency: 'ALL', fullName: 'Albanian Lek' },
  { currency: 'AMD', fullName: 'Armenian Dram' },
  { currency: 'ANG', fullName: 'Netherlands Antillean Guilder' },
  { currency: 'AOA', fullName: 'Angolan Kwanza' },
  { currency: 'ARS', fullName: 'Argentine Peso' },
  { currency: 'AUD', fullName: 'Australian Dollar' },
  { currency: 'AWG', fullName: 'Aruban Florin' },
  { currency: 'AZN', fullName: 'Azerbaijani Manat' },
  { currency: 'BAM', fullName: 'Bosnia-Herzegovina Convertible Mark' },
  { currency: 'BBD', fullName: 'Barbadian Dollar' },
  { currency: 'BDT', fullName: 'Bangladeshi Taka' },
  { currency: 'BGN', fullName: 'Bulgarian Lev' },
  { currency: 'BHD', fullName: 'Bahraini Dinar' },
  { currency: 'BIF', fullName: 'Burundian Franc' },
  { currency: 'BMD', fullName: 'Bermudian Dollar' },
  { currency: 'BND', fullName: 'Brunei Dollar' },
  { currency: 'BOB', fullName: 'Bolivian Boliviano' },
  { currency: 'BRL', fullName: 'Brazilian Real' },
  { currency: 'BSD', fullName: 'Bahamian Dollar' },
  { currency: 'BTN', fullName: 'Bhutanese Ngultrum' },
  { currency: 'BWP', fullName: 'Botswanan Pula' },
  { currency: 'BYN', fullName: 'Belarusian Ruble' },
  { currency: 'BZD', fullName: 'Belize Dollar' },
  { currency: 'CAD', fullName: 'Canadian Dollar' },
  { currency: 'CDF', fullName: 'Congolese Franc' },
  { currency: 'CHF', fullName: 'Swiss Franc' },
  { currency: 'CLP', fullName: 'Chilean Peso' },
  { currency: 'CNY', fullName: 'Chinese Yuan' },
  { currency: 'COP', fullName: 'Colombian Peso' },
  { currency: 'CRC', fullName: 'Costa Rican Colón' },
  { currency: 'CUP', fullName: 'Cuban Peso' },
  { currency: 'CVE', fullName: 'Cape Verdean Escudo' },
  { currency: 'CZK', fullName: 'Czech Republic Koruna' },
  { currency: 'DJF', fullName: 'Djiboutian Franc' },
  { currency: 'DKK', fullName: 'Danish Krone' },
  { currency: 'DOP', fullName: 'Dominican Peso' },
  { currency: 'DZD', fullName: 'Algerian Dinar' },
  { currency: 'EGP', fullName: 'Egyptian Pound' },
  { currency: 'ERN', fullName: 'Eritrean Nakfa' },
  { currency: 'ETB', fullName: 'Ethiopian Birr' },
  { currency: 'FJD', fullName: 'Fijian Dollar' },
  { currency: 'FKP', fullName: 'Falkland Islands Pound' },
  { currency: 'FOK', fullName: 'Faroese Króna' },
  { currency: 'GBP', fullName: 'British Pound Sterling' },
  { currency: 'GEL', fullName: 'Georgian Lari' },
  { currency: 'GGP', fullName: 'Guernsey Pound' },
  { currency: 'GHS', fullName: 'Ghanaian Cedi' },
  { currency: 'GIP', fullName: 'Gibraltar Pound' },
  { currency: 'GMD', fullName: 'Gambian Dalasi' },
  { currency: 'GNF', fullName: 'Guinean Franc' },
  { currency: 'GTQ', fullName: 'Guatemalan Quetzal' },
  { currency: 'GYD', fullName: 'Guyanaese Dollar' },
  { currency: 'HKD', fullName: 'Hong Kong Dollar' },
  { currency: 'HNL', fullName: 'Honduran Lempira' },
  { currency: 'HRK', fullName: 'Croatian Kuna' },
  { currency: 'HTG', fullName: 'Haitian Gourde' },
  { currency: 'HUF', fullName: 'Hungarian Forint' },
  { currency: 'IDR', fullName: 'Indonesian Rupiah' },
  { currency: 'ILS', fullName: 'Israeli New Shekel' },
  { currency: 'IMP', fullName: 'Isle of Man Pound' },
  { currency: 'INR', fullName: 'Indian Rupee' },
  { currency: 'IQD', fullName: 'Iraqi Dinar' },
  { currency: 'IRR', fullName: 'Iranian Rial' },
  { currency: 'ISK', fullName: 'Icelandic Króna' },
  { currency: 'JEP', fullName: 'Jersey Pound' },
  { currency: 'JMD', fullName: 'Jamaican Dollar' },
  { currency: 'JOD', fullName: 'Jordanian Dinar' },
  { currency: 'JPY', fullName: 'Japanese Yen' },
  { currency: 'KES', fullName: 'Kenyan Shilling' },
  { currency: 'KGS', fullName: 'Kyrgystani Som' },
  { currency: 'KHR', fullName: 'Cambodian Riel' },
  { currency: 'KID', fullName: 'Kiribati Dollar' },
  { currency: 'KMF', fullName: 'Comorian Franc' },
  { currency: 'KRW', fullName: 'South Korean Won' },
  { currency: 'KWD', fullName: 'Kuwaiti Dinar' },
  { currency: 'KYD', fullName: 'Cayman Islands Dollar' },
  { currency: 'KZT', fullName: 'Kazakhstani Tenge' },
  { currency: 'LAK', fullName: 'Laotian Kip' },
  { currency: 'LBP', fullName: 'Lebanese Pound' },
  { currency: 'LKR', fullName: 'Sri Lankan Rupee' },
  { currency: 'LRD', fullName: 'Liberian Dollar' },
  { currency: 'LSL', fullName: 'Lesotho Loti' },
  { currency: 'LYD', fullName: 'Libyan Dinar' },
  { currency: 'MAD', fullName: 'Moroccan Dirham' },
  { currency: 'MDL', fullName: 'Moldovan Leu' },
  { currency: 'MGA', fullName: 'Malagasy Ariary' },
  { currency: 'MKD', fullName: 'Macedonian Denar' },
  { currency: 'MMK', fullName: 'Myanmar Kyat' },
  { currency: 'MNT', fullName: 'Mongolian Tugrik' },
  { currency: 'MOP', fullName: 'Macanese Pataca' },
  { currency: 'MRU', fullName: 'Mauritanian Ouguiya' },
  { currency: 'MUR', fullName: 'Mauritian Rupee' },
  { currency: 'MVR', fullName: 'Maldivian Rufiyaa' },
  { currency: 'MWK', fullName: 'Malawian Kwacha' },
  { currency: 'MXN', fullName: 'Mexican Peso' },
  { currency: 'MYR', fullName: 'Malaysian Ringgit' },
  { currency: 'MZN', fullName: 'Mozambican Metical' },
  { currency: 'NAD', fullName: 'Namibian Dollar' },
  { currency: 'NGN', fullName: 'Nigerian Naira' },
  { currency: 'NIO', fullName: 'Nicaraguan Córdoba' },
  { currency: 'NOK', fullName: 'Norwegian Krone' },
  { currency: 'NPR', fullName: 'Nepalese Rupee' },
  { currency: 'NZD', fullName: 'New Zealand Dollar' },
  { currency: 'OMR', fullName: 'Omani Rial' },
  { currency: 'PAB', fullName: 'Panamanian Balboa' },
  { currency: 'PEN', fullName: 'Peruvian Nuevo Sol' },
  { currency: 'PGK', fullName: 'Papua New Guinean Kina' },
  { currency: 'PHP', fullName: 'Philippine Peso' },
  { currency: 'PKR', fullName: 'Pakistani Rupee' },
  { currency: 'PLN', fullName: 'Polish Złoty' },
  { currency: 'PYG', fullName: 'Paraguayan Guarani' },
  { currency: 'QAR', fullName: 'Qatari Rial' },
  { currency: 'RON', fullName: 'Romanian Leu' },
  { currency: 'RSD', fullName: 'Serbian Dinar' },
  { currency: 'RUB', fullName: 'Russian Ruble' },
  { currency: 'RWF', fullName: 'Rwandan Franc' },
  { currency: 'SAR', fullName: 'Saudi Riyal' },
  { currency: 'SBD', fullName: 'Solomon Islands Dollar' },
  { currency: 'SCR', fullName: 'Seychellois Rupee' },
  { currency: 'SDG', fullName: 'Sudanese Pound' },
  { currency: 'SEK', fullName: 'Swedish Krona' },
  { currency: 'SGD', fullName: 'Singapore Dollar' },
  { currency: 'SHP', fullName: 'Saint Helena Pound' },
  { currency: 'SLE', fullName: 'Sierra Leonean Leone' },
  { currency: 'SLL', fullName: 'Sierra Leonean Leone' },
  { currency: 'SOS', fullName: 'Somali Shilling' },
  { currency: 'SRD', fullName: 'Surinamese Dollar' },
  { currency: 'SSP', fullName: 'South Sudanese Pound' },
  { currency: 'STN', fullName: 'São Tomé and Príncipe Dobra' },
  { currency: 'SYP', fullName: 'Syrian Pound' },
  { currency: 'SZL', fullName: 'Swazi Lilangeni' },
  { currency: 'THB', fullName: 'Thai Baht' },
  { currency: 'TJS', fullName: 'Tajikistani Somoni' },
  { currency: 'TMT', fullName: 'Turkmenistani Manat' },
  { currency: 'TND', fullName: 'Tunisian Dinar' },
  { currency: 'TOP', fullName: "Tongan Pa'anga" },
  { currency: 'TRY', fullName: 'Turkish Lira' },
  { currency: 'TTD', fullName: 'Trinidad and Tobago Dollar' },
  { currency: 'TVD', fullName: 'Tuvaluan Dollar' },
  { currency: 'TWD', fullName: 'New Taiwan Dollar' },
  { currency: 'TZS', fullName: 'Tanzanian Shilling' },
  { currency: 'UAH', fullName: 'Ukrainian Hryvnia' },
  { currency: 'UGX', fullName: 'Ugandan Shilling' },
  { currency: 'USD', fullName: 'United States Dollar' },
  { currency: 'UYU', fullName: 'Uruguayan Peso' },
  { currency: 'UZS', fullName: 'Uzbekistan Som' },
  { currency: 'VES', fullName: 'Venezuelan Bolívar' },
  { currency: 'VND', fullName: 'Vietnamese Dong' },
  { currency: 'VUV', fullName: 'Vanuatu Vatu' },
  { currency: 'WST', fullName: 'Samoan Tala' },
  { currency: 'XAF', fullName: 'Central African CFA Franc' },
  { currency: 'XCD', fullName: 'East Caribbean Dollar' },
  { currency: 'XDR', fullName: 'Special Drawing Rights' },
  { currency: 'XOF', fullName: 'West African CFA Franc' },
  { currency: 'XPF', fullName: 'CFP Franc' },
  { currency: 'YER', fullName: 'Yemeni Rial' },
  { currency: 'ZAR', fullName: 'South African Rand' },
  { currency: 'ZMW', fullName: 'Zambian Kwacha' },
  { currency: 'ZWL', fullName: 'Zimbabwean Dollar' },
];
